### ISSUE TITLE
Traps stop working

### ISSUE THREAD

**Issue by irunonayran** [reloZid/android-anuto#10]
My strategy for level 41 with a lot of self healing star enemies is to set up an array of pulling traps. After some time they seem not to entrap new enemies within range. Is that so and if it is, is it on purpose?

**Comment by est31** [comment]
Yeah, I've experienced that as well.

**Comment by reloZid** [comment]
That is on purpose: An enemy can be teleported just once by a trap. The reason is that i didn't want to have never ending waves (too many teleporters and attacking towers not able to beat down healers). Earlier an enemy could be teleported just once generally, that made the mechanism more obvious, but also made the traps much less useful, so I decided to switch to the current solution.

What do you think how this should work?

**Comment by irunonayran** [comment]
Ok sorry, I used them for the first time late in the game when things are less clear so the mechanism was not apparent to me. Now that I know it, it's alright.
