### ISSUE TITLE
The new dropdown-menu...

### ISSUE THREAD

**Issue by halbkernprozessor** [reloZid/android-anuto#112]
...isnt helpful at all. It covers the game area and you cant get quickly, how much points you still can spend.
Thx for your great, inspiring, creative work!

**Comment by reloZid** [comment]
I don't really like it either to be honest. For most users it adds just an extra click to place a tower. But I had multiple users reporting that they were not able to play the game since the menu and speed buttons were added (see [this comment](https://github.com/reloZid/android-anuto/issues/100#issuecomment-319868636)).

The dropdown menu would be needed anyway if someone wanted to add a new tower type. That's why I didn't want to spend time into making the dropdown menu appear depending on the screen size.

If you have suggestions how to better solve this problem, please let me know.

**Comment by MidUK** [comment]
Would it be possible to shrink the icons for the towers?

Also, could Next Wave be shortened to Next? 

I know this isn't a proper fix but for me, the additional click to add a tower makes the game unplayable (I play at x4 speed only and the extra click slow me down enough that I run out of lives before level 83 now).

This is a great game - thanks for all your hard work!

**Comment by Kunvp** [comment]
I too stopped playing. (Although not at 83, I only once made it to level 71. 😃)
Please consider my suggestions:
- Maybe 'next wave' could be replaced by a neat pencil drawn arrow?
- 'menu' to be replaced by a squared hamburger menu style icon? 
- the x1/x4 button can become narrower too.
Personally, at this moment no need for extra tower types.

Finally, thanks for all your  work. I really like it.

**Comment by Kunvp** [comment]
If a  the above  is not sufficient I suggest the build button to open/close a floating box that can be dragged around.
Shopping so once can open the box, build some towers, drag the box aside and build some more towers.
Tapping the build button closes the box.

**Comment by reloZid** [comment]
Finally made the "Build Tower" button show up only if the screen is not large enough. It's included in v0.3-5 which is now in beta.
