### ISSUE TITLE
How to defeat fliers in wave 68 and up?

### ISSUE THREAD

**Issue by pikim** [reloZid/android-anuto#122]
What's the best strategy against fliers in waves above 68? I never managed to get beyond 72, although trying different strategies. Bullet hoses and rockets do only little damage and the fliers are too fast to get them.

**Comment by estemon** [comment]
I've raised level 74, but it's almost impossible to stay there. I think there's no more strategies, enemies power is so high to fight them.

![screenshot_20180422-154404](https://user-images.githubusercontent.com/30245187/39096639-2e738a96-4653-11e8-8349-1195638dc81f.png)

**Comment by mdanchenk** [comment]
![screenshot_2018-06-08-07-30-46](https://user-images.githubusercontent.com/40184152/41257806-db02c5b0-6dd6-11e8-8070-02f9e267af0f.png)

![screenshot_2018-06-08-07-36-43](https://user-images.githubusercontent.com/40184152/41257448-88bd1400-6dd5-11e8-8f7e-ccda2a842859.png)
Same trouble, but on 82wave. Speedy 5angels flyers so powerful,  it  cannot be destroyed at all. I try to fight with gun 3, but result the same. Gun3 is powerful only with many crips in one point. For stand alone crips gun1 is more powerful, just calculate damageinsecond... so, how ro fighting on wave 82 and above is real question.

**Comment by Acters** [comment]
Aside from unlocking the enhancing options. How do we progress further if our layout limits our tower placements and our upgrades/enhancements are limited too? Do I progressively change most of the gun 1towers to gun 3 upgrade 3 missile towers? Even then, what would we do to improve? it would be nice to have an option to increase map size to spread out the damage or a way to build immensely tall. 
The gun 4 tower enhancements stop too soon to handle these higher levels flyers. its tier 2 upgrade is a shame as the increase in its effect is still not high enough for these later levels and only does one tile spray instead of all around.
Aside for my fun being limited by map size and tower enhancement/upgrades, I love this game.

**Comment by krizoek** [comment]
i managed to get to 2.2million once, but i don't recall fully how i did it

**Comment by ChristophHaag** [comment]
I agree, it feels like the strength of the fliers is scaling more than the amount of gold you get so it feels like there isn't any tactics to keep them in check, eventually they will just screw you over because you can't slow them.
![screenshot_20180803-140533](https://user-images.githubusercontent.com/781076/43642057-597b2e28-9726-11e8-80ad-df6a18cdd3f8.png)
That's 5 maxed rapid fire towers and 2 maxed splash towers. It feels like you have to plan literally your entire game on focusing damage on late game fliers.

That means mass slow towers at the start, alternating "first" and "closest" attack strategy. They will keep everything but fliers stuck to the beginning, so the dmg towers can be set to "first" and kill off the fliers first. It works well enough for a while but at some point there simply isn't enough money to do enough damage on the fliers anymore.

**Comment by reloZid** [comment]
With version 0.4 there was a bigger change in balancing. The goal was to avoid that you are being limited by the map size because you don't have enough space left to create a strategical tower placement. Also I wanted the tier 1 and tier 2 towers to be more important during early and mid game. This is why it is much more expensive now to get to the next tier. But I think it addresses the two issues pretty well (comparing the last two screenshots which are probably from 0.4 and 0.3).

It seems like currently you are going to lose mostly because of the fliers in higher levels. I see two ways to address this: Nerf the fliers in terms of health or speed. Nerf the slow-down towers such that all other units get more dangerous too.

I disagree that the game should be playable indefinitely. It would make no longer sense to record any score. Also I imagine it to be disappointing once you realize that the game will never end. And even if someone had the time to create tier 4, tier 5... towers, at some point the towers would need unlimited enhancements because otherwise you could not spend your money forever.

In my opinion the goal is that one game isn't too short such that you run out of ideas pretty fast and also isn't too long such that it feels tedious to start from the beginning again. And most important there should be many different strategies where some of them or good and some of them are bad. The best thing to improve the last point would probably be adding new towers/enemies.

**Comment by hyiltiz** [comment]
I played 0.4-1 *after* the balancing tweaks. I agree some nerfing should be on the way. I wonder if you can run the game in simulation mode where you do not have to render any graphics and just do game logics. In that way, you can just balance the game state parameters via simulation. 

I agree that you should lose in this game since there is no ultimate goal other than getting a score in the end, and the end should happen eventually. But it would be much more interesting to lose because of inefficiencies in resource management or some strategical mistakes in game, rather than being restricted by the growth of game mechanics such as resource and mob perks; i.e. regardless of the strategy applied, however hard you try, you just don't have enough money to upgrade techs to defend.

I may be able to run some of your simulations if it can run without too much dependencies and without graphics rendering.

**Comment by krizoek** [comment]
![screenshot_anuto_td_20180821-205149](https://user-images.githubusercontent.com/709070/44486752-c3f6df80-a654-11e8-9ca2-7cf1a955b429.png)
having some troubles getting past 6mill with the update. anyone else here who experience the same trouble?

**Comment by reloZid** [comment]
Moving to #142.
