### ISSUE TITLE
Stars emerge endlessly

### ISSUE THREAD

**Issue by AlexisCaffa** [reloZid/android-anuto#13]
Sometimes, on Wave 41, the stars emerge endlessly in middle of the track.
They never stop (and think that they are stronger)
v0.1-4

**Comment by ubershy** [comment]
Can confirm! It happens only on wave 41. Even after all my lifes were lost, the stars continued appearing endlessly until I decided to turn the game off.
Also they have insane amount of health, only my consuming turrets were able to keep them off for some time.
Or maybe this behavior of game is made by design?

**Comment by mvdan** [comment]
I've gotten past wave 41 twice and haven't seen this. Sure there are a lot of stars, but they eventually stop.

Note that one turret (the fourth one at max level) teleports enemies backward, which might explain this "emerge endlessly in the middle of the track".

**Comment by AlexisCaffa** [comment]
hahaha could be the turret...

**Comment by ubershy** [comment]
Yes, it could be the turret. Thanks.
