### ISSUE TITLE
Sometime the nextwave button is to long inactive

### ISSUE THREAD

**Issue by Mannshoch** [reloZid/android-anuto#146]
I do not know how the next-wave button work, but sometimes I'm blocked from using it even I wish to. 
Last time how ever, I had to wait until only around 10 enemies where active until i was able to get the next wave. And this was in a phase where I wished to have an average around 100 +- 20 enemies.

Please change the delay to around 5s (real time). And if possible, please show in a little notification how many Enemies came next time I hit the button.

**Comment by reloZid** [comment]
The logic is to block for 5s and as long as there are 3 waves active simultaneously. Probably your 10 remaining enemies were from 3 different waves. We can discuss to remove this restriction. I implemented it because I wanted to avoid having huge amounts of enemies active (for performance reasons) and to avoid exploiting the bonus mechanism too much.

**Comment by Mannshoch** [comment]
It was my intention to "use" this bonus system :-), I need some money to be able to get better towers and be able to reach higher Levels.
May you set this three wave limit until a certain count of enemy. other way you set a timepenalty and reduce the x4 speed to x2 if a fourth wave get started, and back to x1 if a fifth, and maybe x0.5 if a sixth wave appear. So you could may save some performance.

**Comment by reloZid** [comment]
Wave limit is removed in v0.5 (currently beta).
