### ISSUE TITLE
Teleport turrets stop working after a while

### ISSUE THREAD

**Issue by cptMikky** [reloZid/android-anuto#45]
At level 56 , which I was unable to beat so far using many different strategies, I finally found one that seems to be feasible: I create an infinite loop using a battery of teleport turrets at the end of the level. While eventually being able to snipe one star once in a while, the teleporters at the end just stop working after a few minutes, letting star enemies pass freely and lose me the game.

Quite frustrating :)

**Comment by cptMikky** [comment]
So I figured out how teleports work but I also found issue #10 and I must disagree with the motive for this behaviour - "The reason is that i didn't want to have never ending waves" - which is more like a "fixing rules to fix a bug". Endless waves are perfectly OK if they are result of player's strategy.

**Comment by bellevin** [comment]
I completely agree with @cptMikky. 
In addition, even if level 56 is feasible, this issue becomes really annoying in upper levels, like around level 70. When one needs to isolate the enemies so that they are completely alone to be able to kill them, the only solution is to have enough teleporters and to regulate the flow by changing their fire strategies or selling some of them. These waves take a long time, but at least they should remain possible to be won. If we can't rely on teleporters, it becomes really harder and it costs money as we are forced to sell the teleporters to buy them again so that they work again.

**Comment by jkufner** [comment]
All other turrets shoot as long as an enemy is in their range. Teleport turret should be the same.

Whether it makes some level possible should not be relevant. Balancing the levels is another issue.

**Comment by reloZid** [comment]
So this is "decided by community" I guess.
