### ISSUE TITLE
Save Game State

### ISSUE THREAD

**Issue by reloZid** [reloZid/android-anuto#6]

**Comment by Almtesh** [comment]
Good idea, that's the only thing that miss the game.

**Comment by tpeg5stan** [comment]
Yes, I agree with it. It is so painful when you accidentally go back to the menu, and ...poof your game has gone.

**Comment by Almtesh** [comment]
If you want to do it simple, for the moment, I suggest you to just save the game's state on the app storage when the app is hidden (the user presses home, or the screen turns off) and restore the game's state (if there's one) from the storage when the app is shown (the user loads the app from the launcher or the recent app menu).
You can make the menu latter.

**Comment by reloZid** [comment]
The intend is just to make sure that you don't loose your current game when minimizing the app. Personally I don't like the idea that you can save the game at any time and go back if you messed something up. That would make the game much less challenging.

**Comment by Almtesh** [comment]
Yes, that's what I meant. I'm waiting for the 0.2…

**Comment by gloryroad1** [comment]
Being able to save the game at the prior level probably would make it less challenging and addictive but restarting from scratch gets old.  Perhaps allowing a single game save at some large step, like every 5, 10 or 15 levels, would compromise between challenge and tedium.

**Comment by ralienpp** [comment]
I was going to open another issue, but I saw this one, so I am adding my rationale in support for this feature here.

* *guilt mitigation* - I played the game last night and when I looked at the watch I realized I was playing for one and a half hours. As you can imagine I felt some remorse because I spent so much time playing it, instead of doing something "more important" with my time. I got to level 56 with a flawless track record (no lives lost), but I had to change my strategy towards the end and called waves earlier and that eventually made me lose - I did that on purpose because otherwise it would take even more time.

* *battery planning* - on multiple occasions I consumed my battery during gameplay and could not realistically go on. I did not anticipate it would be a success and last that long, so it didn't occur to me that I first should have ensured there was a power source nearby.

Having said that, I suggest a save function that does not remove the fun element from the game, but also addresses the points above.

- When the state is saved, the player can quit the game, then start it again and resume it.
- Resuming will _delete_ the saved state
- And any time, you can save it and quit


This prevents the player from cheating by starting from the same state over and over again, but it addresses the problems I mentioned without making it less challenging.

**Comment by bernhardreiter** [comment]
Hi,
this issue may be about several things at once, what I'd need and strongly suggest is a possibility to resume a game later (even after a device restart). It is important to make the game playable because otherwise for long games I am forced to quit if I run out of time or battery. Having played this game with children I can say that they are very frustrated when they have to quit a game because of a time limit.

(Thanks for creating Anuto as Free Software!)

**Comment by azzamsa** [comment]
this is what I wait from the first time.

**Comment by Mistercraft38** [comment]
Idea to do this : save game state with the android's sharedpreferences library

**Comment by treakiandroid** [comment]
Just opened amd closed a new issue (#120 save and restore playing field) for that, guess my text better gose here...

Would be really grate if you wouldnt loose all yor progress on reboot, androids oom that is doing things before oo (nearly akways) or accidentally swipe away the app in the overview of opened apps (asvi just did to get to the browser still opened with a little less scrolling... 😡😠😕😒)...

Could sure be done very simple by deserialise the playing field every time the activiti respawns from local file and build a thread that serialises the game field every 42 secounds and when the activity is closed or becames inactive. Just search the web for java object serialisation...

Thanks a lot in advance

**Comment by reloZid** [comment]
Done: v0.4 saves the game on pause (opening menu) or closing the application. An existing game is loaded during startup.

**Comment by reloZid** [comment]
Discussions about saving/loading manually goes into #138.
